"""Integration tests against the Base Sepolia testnet.

These tests are SKIPPED automatically unless the environment variable
MOLTBUNKER_TESTNET_PRIVATE_KEY is set (typically via a GitHub Actions secret).
They verify that the SDK can authenticate, retrieve wallet state, and query
threat-level data against a live endpoint — proving the SDK works end-to-end.

Run locally:
    MOLTBUNKER_TESTNET_PRIVATE_KEY=0x... pytest tests/test_integration_testnet.py -v
    """
    import os

    import pytest

    from moltbunker import Client
    from moltbunker.exceptions import AuthenticationError, MoltbunkerError

    TESTNET_BASE_URL = "https://api.moltbunker.com/v1"
    PRIVATE_KEY = os.environ.get("MOLTBUNKER_TESTNET_PRIVATE_KEY")

    # Skip the entire module unless the secret is present
    pytestmark = pytest.mark.skipif(
        not PRIVATE_KEY,
            reason=(
                    "MOLTBUNKER_TESTNET_PRIVATE_KEY not set. "
                            "Set this env-var (Base Sepolia key with test BUNKER) to run live tests."
                                ),
                                )


                                @pytest.fixture(scope="module")
                                def testnet_client() -> Client:
                                    """Return an authenticated Client pointing at the testnet API."""
                                        assert PRIVATE_KEY, "Private key must be set to reach this fixture"
                                            return Client(
                                                    private_key=PRIVATE_KEY,
                                                            base_url=TESTNET_BASE_URL,
                                                                )


                                                                class TestTestnetConnectivity:
                                                                    """Smoke tests: can we reach the API at all?"""

                                                                        def test_get_wallet_balance_returns_valid_response(self, testnet_client: Client) -> None:
                                                                                """get_balance() should return a WalletBalance without raising."""
                                                                                        balance = testnet_client.get_balance()
                                                                                                # The balance object must expose the expected attributes
                                                                                                        assert hasattr(balance, "bunker_balance"), "WalletBalance missing bunker_balance"
                                                                                                                assert isinstance(balance.bunker_balance, (int, float)), (
                                                                                                                            f"bunker_balance should be numeric, got {type(balance.bunker_balance)}"
                                                                                                                                    )
                                                                                                                                            assert balance.bunker_balance >= 0, "Balance cannot be negative"
                                                                                                                                            
                                                                                                                                                def test_get_threat_level_returns_valid_response(self, testnet_client: Client) -> None:
                                                                                                                                                        """get_threat_level() should return a ThreatLevel without raising."""
                                                                                                                                                                threat = testnet_client.get_threat_level()
                                                                                                                                                                        assert hasattr(threat, "level"), "ThreatLevel missing level"
                                                                                                                                                                                assert hasattr(threat, "score"), "ThreatLevel missing score"
                                                                                                                                                                                        assert 0.0 <= threat.score <= 1.0, (
                                                                                                                                                                                                    f"Threat score {threat.score} is outside the expected 0.0-1.0 range"
                                                                                                                                                                                                            )
                                                                                                                                                                                                                    valid_levels = {"unknown", "low", "medium", "high", "critical"}
                                                                                                                                                                                                                            assert threat.level in valid_levels, (
                                                                                                                                                                                                                                        f"Unexpected threat level: {threat.level!r}. Expected one of {valid_levels}"
                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                    def test_list_containers_returns_list(self, testnet_client: Client) -> None:
                                                                                                                                                                                                                                                            """list_containers() should return a list (possibly empty on a fresh testnet wallet)."""
                                                                                                                                                                                                                                                                    containers = testnet_client.list_containers()
                                                                                                                                                                                                                                                                            assert isinstance(containers, list), (
                                                                                                                                                                                                                                                                                        f"Expected list from list_containers(), got {type(containers)}"
                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                    def test_authenticated_request_carries_correct_headers(
                                                                                                                                                                                                                                                                                                            self, testnet_client: Client
                                                                                                                                                                                                                                                                                                                ) -> None:
                                                                                                                                                                                                                                                                                                                        """Verify that our wallet auth strategy injects an Authorization header.
                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                We do this by inspecting the auth strategy directly rather than making
                                                                                                                                                                                                                                                                                                                                        a network round-trip, so this test stays fast even with network latency.
                                                                                                                                                                                                                                                                                                                                                """
                                                                                                                                                                                                                                                                                                                                                        from moltbunker.auth import WalletAuth
                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                auth = WalletAuth(PRIVATE_KEY)  # type: ignore[arg-type]
                                                                                                                                                                                                                                                                                                                                                                        headers = auth.get_auth_headers()
                                                                                                                                                                                                                                                                                                                                                                                assert "Authorization" in headers, "WalletAuth did not produce an Authorization header"
                                                                                                                                                                                                                                                                                                                                                                                        assert headers["Authorization"].startswith("Bearer "), (
                                                                                                                                                                                                                                                                                                                                                                                                    "Authorization header should be a Bearer token"
                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                            class TestTestnetErrorHandling:
                                                                                                                                                                                                                                                                                                                                                                                                                """Verify that the SDK surfaces API errors correctly on testnet."""
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                    def test_invalid_container_id_raises_not_found(self, testnet_client: Client) -> None:
                                                                                                                                                                                                                                                                                                                                                                                                                            """Requesting a non-existent container should raise NotFoundError or MoltbunkerError."""
                                                                                                                                                                                                                                                                                                                                                                                                                                    from moltbunker.exceptions import NotFoundError
                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                            with pytest.raises((NotFoundError, MoltbunkerError)):
                                                                                                                                                                                                                                                                                                                                                                                                                                                        testnet_client.get_container("mb-does-not-exist-99999")
                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                            def test_bad_private_key_raises_authentication_error(self) -> None:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    """A malformed private key should fail at auth time, not with a generic exception."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            with pytest.raises((AuthenticationError, MoltbunkerError, ValueError)):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        bad_client = Client(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        private_key="0xDEADBEEF",  # not a valid 32-byte key
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        base_url=TESTNET_BASE_URL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Trigger an authenticated request
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            bad_client.get_balance()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
